name: checkout_repo
on: push
jobs: 
  checkout-myrepo :
    runs-on: ubuntu-latest
    steps: 
      - name: "install git"
        run: sudo apt install -y git
      - name: "clone repository"
        run: git clone https://github.com/docker-library/hello-world.git
      - name: "listing directory"
        run: ls