name: runner-hello
on: 
  push:
    branches:
      - running-hello-world
jobs: 
  runner-job:
    runs-on: computer-local
    steps:
      - name: "runner hello world"
        run: echo "hello world"