name: test
on: pul-request
jobs: 
  my-job:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
      - name: "testing"
        run: go test -v
      - name: "linting"
        run: go linting -