name: test
on: pull_request
jobs: 
  my-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
      - name: "testing"
        run: go test -v
      - name: "lintings"
        run: go fmt .